export const APP_VERSION = '5';

export interface ChangelogEntry {
  date: string;
  version: string;
  improvements: string[];
  bugFixes: string[];
  updates: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    date: '2026-06-06',
    version: '5',
    improvements: [
      'Launched SurePay integration with payCode-only auth, live payment monitor, cross-term overflow redistribution, and Payment ID cards on fees collection',
      'Integrated Wiza SMS v1 API with live balance header, recharge flow, SMS templates CRUD, scheduled sends (once/weekly/multi-date), and server-side API proxies',
      'Redesigned timetable with compact pill toolbars, live period tracker, multi-profile dashboard sync, and improved day/week view navigation',
      'Added canonical finance summary service for consistent family and pupil fee totals across collection, banking, and requirements pages',
      'Enhanced dashboard with animated 3D stat cards, live timetable tracker, gradient clock, and expandable attendance pupil sub-menu',
      'Modernized events and calendar with cache-first loading, auto term detection, multi-date all-day support, and fluorescent 3D header buttons',
      'Redesigned exams schedule modal with sectioned cards and improved target class selection',
      'Added pupil fees header badges for active assignments and uniform tracking, plus siblings quick-switch dropdown',
      'Overhauled procurement with sticky header, global search toolbar, and dynamic week/month view period selectors',
      'Enhanced bulk SMS with unified More dropdown, balance capacity indicators, and compact recipient selection UI',
      'Added SmartBackButton across the app for context-aware navigation instead of static back links',
      'Improved pupils list with stacked class codes, mobile layout refinements, codes filtering, and advanced search filters (class, section, gender, status)',
      'Added session permission refresh with stale-session banner when role data cannot be confirmed from the database',
      'Expanded history log with security/sensitive category filters, summary stats cards, and richer action/entity labels',
      'Added PLE snapshot recapture plus results sort, search, and subject reorder tools',
      'Rebuilt attendance PDF reports with browser-native printing, day summaries, excluded-days logic, and smart date-based pupil filtering',
      'Made WhatsApp group link editable from About School settings',
      'Separated dashboard and reports into their own module permission groups with timetable access controls',
      'Added pupil status filter on fee assignment page',
      'Added structured logger utility and reusable confirm dialog for destructive actions',
    ],
    bugFixes: [
      'Fixed multi-fee carry forward payments not registering correctly across previous balance items',
      'Fixed carry forward payments not applying to previous term balances during fee processing',
      'Fixed carry forward payment double-counting in previous balance fee creation',
      'Fixed family accounts page missing assignment and lunch fees due to stale fee structure closure',
      'Fixed SurePay zero-fee-match bug by using full fee structures and date-based year/term detection instead of stale isActive flags',
      'Fixed events and calendar all-day date off-by-one errors for UTC+ timezones',
      'Fixed dashboard attendance graph double-counting and inconsistent class name display',
      'Fixed view attendance to only show pupils active on the selected date',
      'Fixed exam history lookup across promoted pupils by searching promotion history, not just current class',
      'Fixed EAT timezone bugs in attendance date saving, comparison, and history ranges',
      'Fixed attendance duplicate Firestore documents on re-recording by switching bulk save to upsert',
      'Fixed Firebase persistent cache primary-lease errors by replacing deprecated persistence API',
      'Fixed infinite re-render loops in notifications and enhanced header components',
      'Fixed SMS API routes crashing on Vercel by removing browser Firebase SDK from server-side handlers',
      'Fixed Wiza SMS iframe/CORS issues with server-fetched balance card and auto-login flow',
      'Fixed timetable horizontal scroll being hijacked while editing periods',
      'Fixed uniform edit modal not pre-filling form data from the selected item',
      'Fixed weekend classes not appearing in dashboard and timetable live trackers',
      'Fixed term and academic year detection using date ranges instead of stale active flags across fees and payments',
      'Fixed duplicate Firestore listeners causing slow navigation and target-id-exists errors',
      'Fixed ChunkLoadError after deployments with graceful client-side recovery',
      'Fixed PLE_SUBJECTS undefined error and snapshot recapture refresh issues',
    ],
    updates: [
      'Guarded debug and maintenance routes behind middleware for production safety',
      'Upgraded Firebase client SDK to ^11.10.0 and pinned modular subpath resolution in Next.js config',
      'Replaced many continuous Firestore onSnapshot listeners with cache-first getDocs and targeted polling to reduce read quota',
      'Optimized dashboard stats route with getCountFromServer and 60-second response cache',
      'Optimized SMS cron fetch with runQuery to reduce daily Firestore reads and mark stuck messages as errors',
      'Enhanced auth cache with TTL, periodic permission refresh, and legacy cache migration',
      'Replaced window.confirm with styled confirm dialogs on uniforms management',
      'Replaced native date inputs with DatePicker component across forms',
      'Improved service worker HTML caching strategy for seamless post-deployment updates',
      'Added fees assignment modal grouping for discounts vs standard fees and multi-fee discount linking',
      'Added payCode field to pupil interface and updated ID card PDF generators with SurePay pay code styling',
      'Added dynamic Wiza SMS credentials stored in Firestore via in-app settings UI',
      'Removed Africa\'s Talking integration; all SMS now routes through Wiza SMS server proxies',
      'Throttled dashboard activity refresh to stop infinite refresh loops',
    ],
  },
  {
    date: '2026-01-27',
    version: '4.5',
    improvements: [
      'Implemented comprehensive snapshot protection system to prevent incorrect data capture',
      'Added automatic snapshot creation via Vercel Cron (daily at 1:00 AM UTC)',
      'Enhanced snapshot validation to detect and prevent incorrect data when pupils are promoted after terms end',
      'Implemented historical data recovery system that prioritizes accurate term-end data',
      'Added promotion detection to identify when pupils were promoted after term ended',
      'Improved snapshot creation with immediate capture window (1 day) and catch-up window (1-2 days)',
      'Enhanced snapshot service with validation and error handling',
      'Added detailed logging for promotion detection and snapshot creation',
    ],
    bugFixes: [
      'Fixed incorrect snapshot data being captured when pupils are promoted after terms end',
      'Fixed snapshots using current class/section instead of term-end class/section',
      'Fixed missing snapshots for terms that ended without automatic creation',
    ],
    updates: [
      'Created automatic snapshot maintenance API endpoint (/api/maintenance/snapshots)',
      'Added checkIfPupilPromotedAfterTerm() method to detect post-term promotions',
      'Added validateSnapshotData() method to validate snapshot data before creation',
      'Enhanced getHistoricalPupilData() to recover accurate term-end data',
      'Updated PupilSnapshotsService with promotion detection and validation',
      'Configured Vercel Cron job for daily automatic snapshot creation',
      'Added snapshot protection documentation (SNAPSHOT_PROTECTION_SETUP.md)',
      'Enhanced snapshot creation flow with validation and historical data recovery',
    ],
  },
  {
    date: '2025-01-01', // Previous date
    version: '4.4',
    improvements: [
      'Optimized Individual Pupil Requirements Modal to load instantly using cached data',
      'Optimized Class Requirements Overview to fetch all pupils\' tracking data at once in single query',
      'Eliminated sequential loading - all pupils\' requirements data now loads simultaneously',
      'Both components now use cached data immediately to prevent loading states',
      'Client-side filtering using cached pupils data for instant results',
      'Consistent behavior across all requirements components matching Requirements Tracking page',
    ],
    bugFixes: [
      'Fixed Individual Pupil Requirements Modal slow loading by removing forced refetch',
      'Fixed Class Requirements Overview loading one pupil at a time - now fetches all at once',
    ],
    updates: [
      'Updated useRequirementTrackingByClass to fetch ALL pupils\' tracking data at once in single query',
      'Updated useRequirementTrackingByPupilAndTerm to use cached data immediately for instant loading',
      'Updated useRequirementTrackingByPupilAndAcademicYear to use cached data immediately',
      'Modified PupilRequirementsModal to work exactly like Requirements Tracking page',
      'Refactored Class Requirements Overview to filter by pupils in class using cached pupils data',
      'All pupils\' requirements data loads at once, not sequentially',
    ],
  },
  {
    date: '2025-12-29', // Previous date
    version: '4.2',
    improvements: [
      'Enhanced PLE (Primary Leaving Examination) results management with integrated display on graduate class page',
      'Added inline PLE results card on pupil details page with beautiful slide-down animation',
      'Improved graduated class page with expandable year groups and individual pupil PLE results',
      'Redesigned all buttons across PLE pages with modern rounded design and hover effects',
      'Added collapsible filters on PLE view results page for better space utilization',
      'Enhanced PLE certificates with grade numbers in words and dynamic ID code display',
      'Improved PLE assessment report with full pupil names, Index Number, and LIN columns',
      'Made pupil names clickable on graduate class page linking to pupil details',
      'Added subject codes (ENG, MATH, SCI, SST) display on PLE results cards',
      'Reorganized school contact information on certificates with improved formatting',
    ],
    bugFixes: [
      'Fixed duplicate PLE results card showing on pupil details page',
      'Fixed PLE results not showing for graduated pupils',
      'Fixed class details page fetching graduated pupils in main list',
      'Fixed PLE assessment report column overflow issues',
      'Fixed certificate photo overlapping with school name',
      'Fixed P.O. Box label duplication on certificates',
    ],
    updates: [
      'Updated "Graduated" badge to "PLE" badge on pupil details page with clickable functionality',
      'Modified class details page to only fetch active pupils, excluding graduated ones',
      'Reorganized graduated class page to display pupils grouped by graduation year in expandable accordions',
      'Integrated PLE Results Management directly into graduated class page with year-based navigation',
      'Added expandable PLE results rows on graduate class page with compact single-row design',
      'Added sorting functionality to PLE view results page with clickable column headers',
      'Added Division "U" (Ungraded) for aggregates 33-36 in PLE results',
      'Converted "Download Batch Certificates" button to "Print" button with Certificates and Assessment options',
      'Created PLE assessment report similar to exam results assessment',
      'Modified PLE certificates to display grade numbers in words (e.g., "C3 (THREE)")',
      'Added dynamic ID codes display on certificates (Index Number, LIN, NIN, etc.)',
      'Updated certificates to hide photo tile when pupil has no photo',
      'Reorganized school contact information on certificates: address (green, double size), phone contacts with TEL label, email and website',
      'Modified PLE assessment report to exclude scores and grading scale',
      'Added full pupil names (Surname, First Name, Other Names) to PLE assessment report',
      'Added Index Number and LIN columns to PLE assessment report',
      'Hidden summary cards on PLE view results page (Total Candidates, Division I, Average Aggregate, Best Performer, Completion Status)',
      'Converted filters to collapsible button on PLE view results page',
      'Moved search bar and filter button to page header actions section',
      'Redesigned all buttons on PLE pages to match modern rounded design with icons and labels',
      'Applied consistent button design across Record PLE Results, PLE Results Management, and Graduate Class pages',
      'Made search bar rounded to match button design',
      'Updated PLE results card to use subject codes instead of full names',
    ],
  },
  {
    date: '2025-12-29', // Previous date
    version: '4.1',
    improvements: [
      'Improved chunk loading error handling with helpful dev server guidance',
      'Reduced console noise by suppressing expected timeout errors',
      'Enhanced error messages to provide actionable solutions for common issues',
      'Improved service worker chunk handling to prevent interference with Next.js chunk loading',
    ],
    bugFixes: [
      'Fixed activeAcademicYear ReferenceError in exams page and class-detail page',
      'Fixed userRole ReferenceError in global-data-preloader component',
      'Fixed infinite reload loop caused by client-side chunk detection',
      'Fixed Next.js Link legacyBehavior deprecation warnings',
      'Fixed service worker intercepting webpack chunks causing 404 errors',
      'Fixed PupilListRow component missing activeAcademicYear and currentTerm props',
    ],
    updates: [
      'Updated Next.js Link components to remove deprecated legacyBehavior prop',
      'Added eslint-disable comments for deprecated APIs (motion factory, enableMultiTabIndexedDbPersistence)',
      'Improved ChunkLoadError handling to suppress uncaught error messages',
      'Enhanced timeout error logging to only show critical collection timeouts',
      'Updated service worker to skip webpack chunk interception for better Next.js compatibility',
      'Added helpful error messages for dev server cache issues with solution guidance',
    ],
  },
  {
    date: '2025-01-27', // Previous date
    version: '4.0',
    improvements: [
      'Redesigned sidebar with hamburger menu button for better space efficiency',
      'Added school logo display when sidebar is collapsed for better branding',
      'Combined version link and sidebar toggle into a single compact button',
      'Improved sidebar footer layout with integrated hamburger menu and version display',
    ],
    bugFixes: [
      'Fixed version text not showing when sidebar is expanded',
      'Fixed sidebar toggle button taking up unnecessary space',
    ],
    updates: [
      'Updated version-link component to include hamburger menu icon',
      'Removed separate DesktopSidebarToggle component for cleaner code',
      'Added conditional logo display in sidebar header for collapsed state',
      'Updated sidebar header to show logo at top when collapsed',
    ],
  },
  {
    date: '2025-12-21', // Previous date
    version: '3.7',
    improvements: [
      'Added automatic push notifications for fee payments to parents and staff',
      'Parents receive instant notifications when their children make fee payments',
      'Staff with fees collection permissions receive notifications for all payments',
      'Notifications include complete payment details: fee item, amounts, balance, time, and receiver',
      'Multi-device support: notifications appear on all devices where users are signed in',
      'Family-based notifications: all parent accounts with same familyId receive notifications',
      'Permission-based filtering: only staff with fees module access receive notifications',
      'Rich notification content with formatted currency and payment status',
      'Non-blocking notification system: payments succeed even if notifications fail',
      'Real-time notification delivery via web push and native FCM',
    ],
    bugFixes: [
      'Fixed Next.js 15 build errors with server-only modules in client bundles',
      'Fixed webpack attempting to bundle Node.js built-in modules (net, tls, http2) for browser',
      'Fixed firebase-admin and web-push being included in client JavaScript bundle',
      'Resolved "Module not found" errors for node:events, node:process, node:stream, node:util',
      'Fixed notification service causing build failures due to server/client code mixing',
    ],
    updates: [
      'Created fees-payment-notification.server.ts for server-only notification logic',
      'Updated PaymentsService.createPayment to automatically trigger notifications',
      'Added server-side check (typeof window) to prevent browser execution',
      'Updated next.config.js for Next.js 15 compatibility (serverExternalPackages)',
      'Added comprehensive webpack fallbacks for Node.js modules',
      'Implemented dynamic imports for server-only modules',
      'Added IgnorePlugin to webpack config to exclude .server.ts files from client bundle',
      'Created getParentsByFamilyId method to retrieve parent accounts',
      'Created getUsersWithFeesPermissions method to get staff with fees access',
      'Integrated with existing optimized-notification.service for delivery',
      'Added balance calculation logic using payment history',
      'Enhanced error handling with detailed logging for debugging',
    ],
  },
  {
    date: '2025-12-06', // Previous date
    version: '3.5',
    improvements: [
      'Added timeout protection (30 seconds) to all Firestore queries to prevent hanging',
      'Implemented cache-first strategy: queries now check cache before server fetch for instant loads',
      'Added retry logic with exponential backoff (2s, 4s, 8s) for timeout errors',
      'Queries now return cached data as fallback when timeouts occur, preventing blank screens',
      'Reduced app load time from 10+ minutes to under 30 seconds on slow networks',
      'Fixed About School page not loading - now always renders immediately with sample data fallback',
      'Improved error handling for Firebase timeout errors with graceful degradation',
      'Dashboard queries now retry automatically on timeout instead of failing completely',
      'All Firestore queries now use Promise.race for timeout enforcement',
      'Cache-first reads are now truly instant - no waiting for server responses when cache exists',
    ],
    bugFixes: [
      'Fixed app taking 10+ minutes to load due to Firebase queries timing out without protection',
      'Fixed About School component not loading - removed blocking loading spinner',
      'Fixed queries hanging indefinitely on slow networks (158+ seconds)',
      'Fixed "The datastore operation timed out" errors causing complete app failures',
      'Fixed queries not using cached data when available, causing unnecessary slow server fetches',
      'Fixed no fallback when queries timeout - app now returns cached data instead of failing',
      'Fixed duplicate queries running simultaneously (all pupils + active pupils) causing conflicts',
      'Fixed getDocsWithTimeout not actually implementing timeout - now uses Promise.race',
      'Fixed cache not being checked first - queries now try cache before server',
    ],
    updates: [
      'Updated getDocsWithTimeout to implement proper timeout with Promise.race (30s default)',
      'Added getDocsFromCache check before server fetch in getDocsWithTimeout for instant cache reads',
      'Implemented retry logic in dashboard pupils query with exponential backoff',
      'Updated firestore-helpers.ts to check cache first, then server, then return cached data on timeout',
      'Added timeout error detection and cached data fallback in getDocsWithTimeout',
      'Updated About School page to always render with sampleSchoolSettings fallback',
      'Removed blocking loading spinner from About School page - now renders immediately',
      'Added useMemo for currentSettings in About School page to ensure it\'s always available',
      'Updated About School page to use flushSync for instant UI updates when Firebase data loads',
      'Enhanced error handling in getDocsWithTimeout to return cached data when queries timeout',
      'Added retry configuration to useDashboardData hook for better resilience',
      'Improved timeout error messages to be more descriptive and actionable',
    ],
  },
  {
    date: '2025-12-01', // Previous date
    version: '2.3',
    improvements: [
      'Massive performance improvements across all data fetching with cache-first strategy',
      'Family accounts page now loads 5-10x faster with parallel data loading for all pupils',
      'Pupils list page displays instantly from cache with client-side filtering (no database queries)',
      'Individual pupil fees collection page loads academic years and fees data instantly from cache',
      'Class details page now loads instantly (< 100ms) from cache with real-time synchronization',
      'Exam record results and view results pages now load instantly (< 100ms) with cached data',
      'Banking pages (accounts list and pupil banking details) now load instantly (< 100ms) with real-time sync',
      'PDF generation for exam results optimized - reduced QR code resolution and added batch processing',
      'Added real-time listeners (onSnapshot) for pupils, classes, staff, subjects, exams, accounts, loans, and transactions',
      'Implemented beautiful loading animations for school settings in sidebar',
      'Optimized all Firestore queries to use native caching instead of custom timeouts',
      'Parallel data loading for family fees: payments, snapshots, fees holidays, and uniform fees load simultaneously',
      'Client-side class filtering on pupils list - instant results without waiting for database queries',
      'Added progress callbacks for PDF generation to show real-time status during batch report creation',
      'Optimized academic years fetching with cache-first strategy and real-time updates',
      'Reduced PDF generation time from 20 minutes to under 2 minutes for 80 pupils with optimized QR codes',
      'Class details page shows cached content immediately even while fetching updates in background',
      'Staff and subjects data now load instantly from cache on class details page',
      'Exam data across the system loads instantly with real-time synchronization',
      'Exam results update in real-time without page refresh when changes are made',
      'Bank account balances, loans, and transactions update instantly in real-time across all pages',
      'Banking system shows cached data immediately while synchronizing updates in background',
    ],
    bugFixes: [
      'Fixed pupils list page showing 0 pupils when class is selected - now uses cached data instantly',
      'Fixed slow loading on pupils list page by removing dependency on slow class-based queries',
      'Fixed individual pupil fees collection page hanging on "Setting up academic year and term"',
      'Fixed Firestore timeout errors by removing custom timeout logic that interfered with native caching',
      'Fixed pupils not being fetched after optimization changes - corrected getDocsWithTimeout return type',
      'Fixed pupils details page slow loading by removing redundant class data fetching',
      'Fixed family accounts page sequential loading - now loads all pupil data in parallel',
      'Fixed PDF generation freezing browser during QR code creation for large batches',
      'Fixed class details page showing loading spinner even when data is cached',
      'Fixed class details page waiting for photos before showing pupils list',
      'Fixed entire system reloading (including sidebar) when navigating between exam pages',
      'Fixed skeleton animation staying visible after pupils data is fetched',
      'Fixed exam record results page showing loading spinner even when exam data is cached',
      'Fixed exam view results page long loading times - now displays cached data instantly',
      'Fixed Firebase import paths in use-class-detail, use-staff, and use-subjects hooks',
      'Fixed banking pages showing loading spinner even when account data is cached',
      'Fixed pupil banking details page waiting for account data before displaying pupil information',
      'Fixed bank account balances not updating in real-time when transactions are made',
    ],
    updates: [
      'Refactored useAcademicYears hook to use optimized cache-first strategy with real-time listeners',
      'Updated usePupils and usePupil hooks with onSnapshot listeners for live data updates',
      'Updated useClasses hook with real-time listeners and optimized caching',
      'Modified PupilsService to use getDocsWithTimeout for cache-first data fetching',
      'Modified ClassesService to use optimized cache-first helpers',
      'Modified AcademicYearsService to use getDocsWithTimeout and getDocWithTimeout',
      'Updated usePupilFees hook to use globally optimized useAcademicYears hook',
      'Optimized usePupilFees to enable parallel loading of fees, payments, and snapshots',
      'Created SchoolSettingsLoader component with beautiful framer-motion animations',
      'Updated ModernBatchReportPDF to use reduced QR code resolution (scale: 8, width: 400)',
      'Added onProgress callback to PDF generation functions for real-time progress updates',
      'Implemented batch processing for QR code generation with small delays to prevent UI freezing',
      'Updated family accounts page to load all pupil data (payments, snapshots, fees holidays, uniform fees) in parallel',
      'Simplified pupils list page to always use cached pupils with client-side filtering',
      'Removed custom timeout wrappers from firestore-helpers.ts - now uses Firestore native caching',
      'Updated all React Query hooks with optimized staleTime, gcTime, and disabled aggressive refetching',
      'Added placeholderData to React Query hooks to keep previous data while fetching new',
      'Optimized useClassDetail hook with onSnapshot listener and cache-first strategy',
      'Optimized useStaff hook with real-time listeners and 5-minute staleTime',
      'Optimized useSubjects hook with real-time listeners and 5-minute staleTime',
      'Added flushSync to class details page for instant DOM updates when data arrives',
      'Removed unused useClassPupilsManager import from class details page',
      'Optimized class details loading state to only show spinner when no cached data exists',
      'Changed class details pupils loading check to show cached pupils immediately',
      'Memoized AppLayout component to prevent sidebar re-renders during navigation',
      'Removed orderBy from pupils onSnapshot query for instant data fetching (773 pupils in 2 queries)',
      'Optimized useExams hook with real-time onSnapshot listeners and cache-first strategy',
      'Optimized useExam hook with real-time listeners for individual exam data',
      'Optimized useExamResultByExamId hook with cache-first strategy and real-time updates',
      'Added flushSync import to RecordResultsView and ViewResultsView for instant UI updates',
      'Updated exam loading states to display cached data immediately while fetching updates',
      'Configured 5-minute staleTime for exams data with 30-minute garbage collection time',
      'Configured 2-minute staleTime for exam results with 15-minute garbage collection time',
      'Optimized useAccountsWithPupils hook with real-time listeners for accounts and pupils',
      'Optimized useAccountByPupilId hook with cache-first strategy and real-time updates',
      'Optimized useLoansByPupilId hook with real-time listeners for instant loan updates',
      'Optimized useTransactionsByPupilId hook with real-time listeners for instant transaction updates',
      'Added flushSync import to banking pages for instant DOM updates',
      'Updated banking loading states to show cached data immediately while fetching updates',
      'Configured 3-minute staleTime for accounts, 2-minute for loans, 1-minute for transactions',
      'Banking hooks now listen to both accounts and pupils collections for comprehensive updates',
    ],
  },
  {
    date: '2025-11-27', // Previous date
    version: '2.2.1',
    improvements: [],
    bugFixes: [
      'Fixed pdfViewer is not defined error on fees collection page by initializing usePDFViewer hook',
    ],
    updates: [],
  },
  {
    date: '2025-11-27', // Previous date
    version: '2.2',
    improvements: [
      'Added Staff-Pupil Assignment (Mofus) feature with centralized management page',
      'Implemented Fees Holiday system for staff privilege discounts with multiple categories and discount types',
      'Created Family Fees Summary page with Summary/Detail view toggle and expandable fee breakdowns',
      'Enhanced all buttons with distinct glossy colors and modern visual effects',
      'Modernized year and term selector into compact glossy card with improved dropdowns',
      'Added clickable pupil and staff names throughout the system linking to detail pages',
      'Created Staff Relative section on pupil detail pages (conditional display)',
      'Created Pupil Relatives section on staff detail pages (conditional display)',
      'Improved fee breakdown display with custom staff privilege messaging',
      'Consolidated family summary into glossy card showing Total Amount, Paid, and Balance',
      'Made pupil cards more compact using class codes and inline PIN display',
      'Removed scrolling from fee breakdown sections with expand/collapse functionality',
      'Enhanced fees collection page with staff privilege discount indicators',
      'Improved previous term balance calculations to exclude fees cleared by staff privilege',
    ],
    bugFixes: [
      'Fixed fees holidays not being detected on Family Fees Summary page',
      'Fixed previous term balances including fees cleared by staff privilege',
      'Fixed duplicate import of useActiveFeesHolidaysByPupil hook causing compilation error',
      'Fixed Firebase index requirement error for fees holidays query by removing orderBy',
      'Fixed HTML validation error (div inside p tag) in fees holiday modal',
      'Fixed Firebase undefined discountValue error by implementing proper data cleaning',
      'Fixed fees holiday reason not showing on fees collection page',
    ],
    updates: [
      'Extended Pupil type with assignedStaffId field for staff-pupil relationships',
      'Updated FeesHoliday type to support multiple categories (array instead of single value)',
      'Added FeesHolidayCategory and FeesHolidayDiscountType types',
      'Updated PupilFee discount type to include fees-holiday with reason and category fields',
      'Created new /staff/mofus page for centralized staff-pupil assignment management',
      'Enhanced processPupilFees function to accept and apply fees holidays',
      'Updated calculatePreviousTermBalances to account for fees holidays in carry-forward',
      'Modified fees-holiday.service.ts to handle category arrays and data cleaning',
      'Updated FeeCard component to display staff privilege information with staff member details',
      'Enhanced Family Fees Summary page with view modes and individual expand controls',
      'Updated staff and pupil detail pages with relative sections',
      'Modernized all button components with gradient backgrounds and enhanced glossy effects',
    ],
  },
  {
    date: '2024-12-26', // Today's date
    version: '2.1',
    improvements: [
      'Added Pending Pupils status management system with configurable component exclusions',
      'Enhanced Class Details page with modern, rounded, and glossy button designs',
      'Implemented multiple subject teachers support for class creation and editing',
      'Added Class Captain and Assistant Class Captain assignment functionality',
      'Created Class History page to view past pupils for any academic year',
      'Added Pending button on Pupils List page that appears when a class with pending pupils is selected',
      'Enhanced Pending Pupils page with Select/Activate workflow for bulk activation',
      'Added Status History tracking with "Returned" reason when pupils are activated from Pending status',
      'Improved pupil avatar display to show photos when available, with fallback to initials',
      'Made subject list display more compact by hiding Type and Code fields',
      'Added History and Graduated Class icon buttons on class detail page',
      'Enhanced Class History page to only show current and past academic years',
      'Updated Current Class column in Class History to display class codes',
      'Added Pending button on Class List page with count badge',
      'Added Pending button on Class Detail page that links to class-specific pending pupils',
      'Configured Time of Effect settings for automatic Pending status activation (End of Term or Beginning of Next Term)',
      'Implemented automatic pending status transition based on Time of Effect setting',
    ],
    bugFixes: [
      'Fixed React.useMemo error on Pupils List page by using imported useMemo hook',
      'Fixed Time of Effect setting not being saved correctly in About School settings',
      'Fixed pending pupils being activated immediately instead of respecting Time of Effect setting',
      'Fixed continue statement error in Class History page by replacing with return statement',
      'Fixed 404 errors for JS files by properly restarting dev server',
      'Fixed Current Class column in Class History to use class code instead of class name',
      'Fixed pending status history reason to show "Returned" when pupils are activated from Pending',
    ],
    updates: [
      'Extended PupilStatus type to include "Pending" status',
      'Updated SubjectAssignment type to support multiple teachers (teacherIds array)',
      'Extended Class type to include classCaptainId and assistantClassCaptainId fields',
      'Enhanced SchoolSettings interface with pending status configuration options',
      'Updated PUPIL_STATUSES constant to include "Pending" status',
      'Added pending-filter utility functions for filtering pupils based on pending status settings',
      'Updated useSubjectsByClass hook to support multiple teachers per subject with backward compatibility',
      'Enhanced About School settings page with Pending Status Management section',
      'Created new /classes/pending page for managing pending pupils',
      'Created new /classes/history/[classId] page for viewing class history',
    ],
  },
  // Add changelog entries here as you make updates
  // Example structure:
  // {
  //   date: '2024-12-20',
  //   version: '2.0',
  //   improvements: ['Improvement 1', 'Improvement 2'],
  //   bugFixes: ['Fixed bug 1', 'Fixed bug 2'],
  //   updates: ['Updated dependency 1'],
  // },
];

